export type FoodCategory = "breakfast" | "lunch" | "dinner" | "snack" | "drink";

export interface FoodCatalogSeedItem {
  slug: string;
  nameThai: string;
  nameEnglish: string;
  category: FoodCategory;
  serving: string;
  calories: number;
  carbsG: number;
  proteinG: number;
  fatG: number;
  fiberG: number;
  sugarG: number;
  sodiumMg: number;
  diabetesFriendly: boolean;
  tags: string[];
}

export const FOOD_CATALOG: FoodCatalogSeedItem[] = [
  {
    slug: "oatmeal-unsweetened",
    nameThai: "ข้าวโอ๊ตต้มไม่หวาน",
    nameEnglish: "Unsweetened Oatmeal",
    category: "breakfast",
    serving: "1 ถ้วย",
    calories: 158,
    carbsG: 27,
    proteinG: 5.5,
    fatG: 3,
    fiberG: 4,
    sugarG: 1,
    sodiumMg: 3,
    diabetesFriendly: true,
    tags: ["wholegrain", "high-fiber", "low-sugar"],
  },
  {
    slug: "whole-wheat-bread-2-slices",
    nameThai: "ขนมปังโฮลวีต 2 แผ่น",
    nameEnglish: "Whole Wheat Bread",
    category: "breakfast",
    serving: "2 แผ่น",
    calories: 142,
    carbsG: 24,
    proteinG: 8,
    fatG: 2,
    fiberG: 4,
    sugarG: 3,
    sodiumMg: 260,
    diabetesFriendly: true,
    tags: ["wholegrain", "moderate-carb"],
  },
  {
    slug: "soy-milk-unsweetened",
    nameThai: "นมถั่วเหลืองไม่หวาน",
    nameEnglish: "Unsweetened Soy Milk",
    category: "drink",
    serving: "250 มล.",
    calories: 95,
    carbsG: 8,
    proteinG: 7,
    fatG: 4,
    fiberG: 1,
    sugarG: 3,
    sodiumMg: 105,
    diabetesFriendly: true,
    tags: ["low-sugar", "plant-protein"],
  },
  {
    slug: "brown-rice-150g",
    nameThai: "ข้าวกล้อง 150 กรัม",
    nameEnglish: "Brown Rice",
    category: "lunch",
    serving: "150 กรัม",
    calories: 166,
    carbsG: 35,
    proteinG: 3.5,
    fatG: 1.3,
    fiberG: 1.8,
    sugarG: 0.3,
    sodiumMg: 2,
    diabetesFriendly: true,
    tags: ["wholegrain", "moderate-carb"],
  },
  {
    slug: "jasmine-rice-150g",
    nameThai: "ข้าวขาว 150 กรัม",
    nameEnglish: "Jasmine Rice",
    category: "lunch",
    serving: "150 กรัม",
    calories: 205,
    carbsG: 45,
    proteinG: 4,
    fatG: 0.4,
    fiberG: 0.4,
    sugarG: 0.1,
    sodiumMg: 1,
    diabetesFriendly: false,
    tags: ["high-glycemic", "refined-carb"],
  },
  {
    slug: "grilled-chicken-breast-120g",
    nameThai: "อกไก่ย่าง 120 กรัม",
    nameEnglish: "Grilled Chicken Breast",
    category: "lunch",
    serving: "120 กรัม",
    calories: 198,
    carbsG: 0,
    proteinG: 36,
    fatG: 4,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 75,
    diabetesFriendly: true,
    tags: ["high-protein", "low-carb"],
  },
  {
    slug: "grilled-salmon-120g",
    nameThai: "แซลมอนย่าง 120 กรัม",
    nameEnglish: "Grilled Salmon",
    category: "dinner",
    serving: "120 กรัม",
    calories: 233,
    carbsG: 0,
    proteinG: 25,
    fatG: 14,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 72,
    diabetesFriendly: true,
    tags: ["omega3", "high-protein", "low-carb"],
  },
  {
    slug: "steamed-fish-lime",
    nameThai: "ปลานึ่งมะนาว",
    nameEnglish: "Steamed Fish with Lime",
    category: "dinner",
    serving: "1 จาน",
    calories: 180,
    carbsG: 6,
    proteinG: 28,
    fatG: 5,
    fiberG: 1,
    sugarG: 2,
    sodiumMg: 340,
    diabetesFriendly: true,
    tags: ["high-protein", "thai-food"],
  },
  {
    slug: "tofu-stir-fry",
    nameThai: "เต้าหู้ผัดผัก",
    nameEnglish: "Tofu Vegetable Stir Fry",
    category: "dinner",
    serving: "1 จาน",
    calories: 205,
    carbsG: 16,
    proteinG: 15,
    fatG: 9,
    fiberG: 4,
    sugarG: 5,
    sodiumMg: 300,
    diabetesFriendly: true,
    tags: ["plant-protein", "high-fiber"],
  },
  {
    slug: "stir-fried-morning-glory",
    nameThai: "ผัดผักบุ้งไฟแดง (น้ำมันน้อย)",
    nameEnglish: "Stir Fried Morning Glory",
    category: "dinner",
    serving: "1 จานเล็ก",
    calories: 96,
    carbsG: 10,
    proteinG: 3.5,
    fatG: 4,
    fiberG: 3,
    sugarG: 3,
    sodiumMg: 190,
    diabetesFriendly: true,
    tags: ["vegetable", "side-dish"],
  },
  {
    slug: "clear-vegetable-soup",
    nameThai: "ต้มจืดผักรวม",
    nameEnglish: "Clear Vegetable Soup",
    category: "dinner",
    serving: "1 ถ้วย",
    calories: 85,
    carbsG: 11,
    proteinG: 6,
    fatG: 2,
    fiberG: 2.5,
    sugarG: 3,
    sodiumMg: 240,
    diabetesFriendly: true,
    tags: ["light", "high-fiber"],
  },
  {
    slug: "papaya-salad-no-sugar",
    nameThai: "ส้มตำไม่ใส่น้ำตาล",
    nameEnglish: "Papaya Salad No Sugar",
    category: "lunch",
    serving: "1 จาน",
    calories: 118,
    carbsG: 16,
    proteinG: 5,
    fatG: 4,
    fiberG: 4,
    sugarG: 7,
    sodiumMg: 410,
    diabetesFriendly: true,
    tags: ["spicy", "high-fiber", "thai-food"],
  },
  {
    slug: "pumpkin-soup",
    nameThai: "ซุปฟักทอง",
    nameEnglish: "Pumpkin Soup",
    category: "lunch",
    serving: "1 ถ้วย",
    calories: 140,
    carbsG: 20,
    proteinG: 4,
    fatG: 4,
    fiberG: 3,
    sugarG: 6,
    sodiumMg: 230,
    diabetesFriendly: true,
    tags: ["moderate-carb", "high-fiber"],
  },
  {
    slug: "boiled-egg-1",
    nameThai: "ไข่ต้ม 1 ฟอง",
    nameEnglish: "Boiled Egg",
    category: "snack",
    serving: "1 ฟอง",
    calories: 70,
    carbsG: 0.4,
    proteinG: 6,
    fatG: 5,
    fiberG: 0,
    sugarG: 0.2,
    sodiumMg: 62,
    diabetesFriendly: true,
    tags: ["high-protein", "low-carb"],
  },
  {
    slug: "greek-yogurt-low-fat",
    nameThai: "กรีกโยเกิร์ตไขมันต่ำ",
    nameEnglish: "Low Fat Greek Yogurt",
    category: "snack",
    serving: "170 กรัม",
    calories: 112,
    carbsG: 8,
    proteinG: 16,
    fatG: 2,
    fiberG: 0,
    sugarG: 6,
    sodiumMg: 65,
    diabetesFriendly: true,
    tags: ["high-protein", "probiotic"],
  },
  {
    slug: "guava-1-fruit",
    nameThai: "ฝรั่ง 1 ผลกลาง",
    nameEnglish: "Guava",
    category: "snack",
    serving: "1 ผลกลาง",
    calories: 68,
    carbsG: 14,
    proteinG: 2.6,
    fatG: 1,
    fiberG: 5.4,
    sugarG: 8,
    sodiumMg: 2,
    diabetesFriendly: true,
    tags: ["fruit", "high-fiber", "vitamin-c"],
  },
  {
    slug: "apple-1-medium",
    nameThai: "แอปเปิล 1 ผลกลาง",
    nameEnglish: "Apple",
    category: "snack",
    serving: "1 ผลกลาง",
    calories: 95,
    carbsG: 25,
    proteinG: 0.5,
    fatG: 0.3,
    fiberG: 4.4,
    sugarG: 19,
    sodiumMg: 2,
    diabetesFriendly: true,
    tags: ["fruit", "fiber"],
  },
  {
    slug: "mixed-nuts-20g",
    nameThai: "ถั่วรวม 20 กรัม",
    nameEnglish: "Mixed Nuts",
    category: "snack",
    serving: "20 กรัม",
    calories: 122,
    carbsG: 6,
    proteinG: 4,
    fatG: 10,
    fiberG: 2,
    sugarG: 1,
    sodiumMg: 2,
    diabetesFriendly: true,
    tags: ["healthy-fat", "low-carb"],
  },
  {
    slug: "banana-small",
    nameThai: "กล้วยหอมผลเล็ก",
    nameEnglish: "Small Banana",
    category: "snack",
    serving: "1 ผลเล็ก",
    calories: 90,
    carbsG: 23,
    proteinG: 1.1,
    fatG: 0.3,
    fiberG: 2.6,
    sugarG: 12,
    sodiumMg: 1,
    diabetesFriendly: false,
    tags: ["fruit", "higher-carb"],
  },
  {
    slug: "mango-sticky-rice",
    nameThai: "ข้าวเหนียวมะม่วง",
    nameEnglish: "Mango Sticky Rice",
    category: "snack",
    serving: "1 ชุด",
    calories: 360,
    carbsG: 66,
    proteinG: 5,
    fatG: 8,
    fiberG: 2,
    sugarG: 38,
    sodiumMg: 150,
    diabetesFriendly: false,
    tags: ["dessert", "high-sugar", "high-carb"],
  },
  {
    slug: "quinoa-salad",
    nameThai: "สลัดควินัว",
    nameEnglish: "Quinoa Salad",
    category: "lunch",
    serving: "1 ชาม",
    calories: 240,
    carbsG: 31,
    proteinG: 9,
    fatG: 8,
    fiberG: 5,
    sugarG: 4,
    sodiumMg: 180,
    diabetesFriendly: true,
    tags: ["high-fiber", "wholegrain", "salad"],
  },
  {
    slug: "lentil-stew",
    nameThai: "สตูว์ถั่วเลนทิล",
    nameEnglish: "Lentil Stew",
    category: "dinner",
    serving: "1 ถ้วย",
    calories: 210,
    carbsG: 32,
    proteinG: 13,
    fatG: 4,
    fiberG: 9,
    sugarG: 3,
    sodiumMg: 220,
    diabetesFriendly: true,
    tags: ["plant-protein", "high-fiber"],
  },
];
